<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_AutomationExercise</name>
   <tag></tag>
   <elementGuidId>6583b7e8-fd8d-4ee0-ba9c-895a9129bf4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//yt-formatted-string[@id='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>99425138-cd09-4974-a156-dd2767bd1090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c72dca9-bc9a-4d45-890c-20237b28b426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytd-channel-name</value>
      <webElementGuid>f5802506-ced9-4139-a0c6-2250ab51dd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AutomationExercise</value>
      <webElementGuid>e1b89b6c-abd2-412f-8651-e643dcf217f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inner-header-container&quot;)/div[@id=&quot;meta&quot;]/ytd-channel-name[@id=&quot;channel-name&quot;]/div[@id=&quot;container&quot;]/div[@id=&quot;text-container&quot;]/yt-formatted-string[@id=&quot;text&quot;]</value>
      <webElementGuid>d5c2f275-402a-47ce-8890-3631045d6982</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id='text']</value>
      <webElementGuid>1df50854-5f9d-4a88-9cfd-cd05841d5f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='text-container']/yt-formatted-string</value>
      <webElementGuid>04847477-fcf0-4992-9713-ef38c9253551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/following::yt-formatted-string[1]</value>
      <webElementGuid>bab8b15f-931f-4e20-8fdf-666ad87d1578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@AutomationExercise'])[1]/preceding::yt-formatted-string[1]</value>
      <webElementGuid>407f8c54-5593-4720-978b-23d7ab6a00c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AutomationExercise']/parent::*</value>
      <webElementGuid>4964bc04-9c15-4f3a-892e-0b30c5737878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ytd-channel-name/div/div/yt-formatted-string</value>
      <webElementGuid>91d81d13-f2a2-4143-8644-3f92ee9d0bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id = 'text' and (text() = 'AutomationExercise' or . = 'AutomationExercise')]</value>
      <webElementGuid>d8cd1c5d-a9d4-40c6-aa0f-58c913c7abf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
