<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MonthJanuaryFebruaryMarchAprilMayJun_aa9ebb</name>
   <tag></tag>
   <elementGuidId>6d4bb2b7-0f9a-435e-8cec-fc104737c132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='months']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#months</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3621df4d-7f31-400d-944b-a9848c5ba8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>492af343-9446-4ef6-b491-39fdb2ee96c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>2cee366d-9be1-4179-ba5d-852982c4c1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>73dd0387-4105-45c4-b53d-47264e8d3756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>94c3745d-32e2-45ea-9330-a78c12b5b2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										</value>
      <webElementGuid>41d098a5-2439-47cc-b347-9d0a4b0df1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;months&quot;)</value>
      <webElementGuid>f1674b67-6b13-4c07-bade-bcfaa8c1dbbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='months']</value>
      <webElementGuid>73029757-8cfd-49c5-ba6b-162c6e237b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-months']/select</value>
      <webElementGuid>86834a29-3545-4c5b-9698-e63c7037af7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::select[2]</value>
      <webElementGuid>fb61190f-8378-49f6-8f48-8e1bb86ab848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[2]</value>
      <webElementGuid>871a5f80-dd59-4923-91b9-bebd7a4c5654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up for our newsletter!'])[1]/preceding::select[2]</value>
      <webElementGuid>43d96911-58c5-43c0-863c-2acc94b03b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receive special offers from our partners!'])[1]/preceding::select[2]</value>
      <webElementGuid>f41868f1-984d-4a9e-a0b8-d3912bffd969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>5138ce63-02a5-4b6e-9e70-e839091ded6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'months' and @name = 'months' and (text() = '
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										' or . = '
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										')]</value>
      <webElementGuid>4845077d-7de3-4f6d-aa0f-0e627f1eecb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
